name: Deploy Rolling Update

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: Tag da imagem Docker (ex. 0.0.2 ou SHA do commit)
        required: true
        default: "0.0.2"

env:
  IMAGE_NAME: thiago-almeida-devops
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_PROJECT_NUMBER: ${{ vars.GCP_PROJECT_NUMBER }}
  GKE_CLUSTER_LOCATION: ${{ vars.GKE_CLUSTER_LOCATION }}
  GKE_CLUSTER_NAME: ${{ vars.GKE_CLUSTER_NAME }}
  K8S_NAMESPACE: ${{ vars.K8S_NAMESPACE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          cluster_name: ${{ vars.GKE_CLUSTER_NAME }}
          location: ${{ vars.GKE_CLUSTER_LOCATION }}

      - name: Render manifests
        env:
          NAMESPACE: ${{ vars.K8S_NAMESPACE }}
          DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ inputs.image_tag }}
          APP_HOST: gremio.local
        run: |
          chmod +x k8s/render.sh
          ./k8s/render.sh

      - name: Apply base manifests
        run: |
          kubectl apply -f k8s/rendered/namespace.yaml
          kubectl apply -f k8s/rendered/deployment.yaml
          kubectl apply -f k8s/rendered/service.yaml
          kubectl apply -f k8s/rendered/hpa.yaml

      - name: Deploy image
        id: deploy_step
        run: |
          kubectl set image deployment/app-satc \
            thiago-almeida-devops=${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ inputs.image_tag }} \
            -n "${{ vars.K8S_NAMESPACE }}"

      - name: Monitor rollout
        id: monitor
        run: |
          kubectl rollout status deployment/app-satc -n "${{ vars.K8S_NAMESPACE }}" --timeout=5m

      - name: Auto rollback on failure
        if: failure() && steps.deploy_step.outcome == 'success'
        run: |
          echo "Deploy falhou! Executando rollback..."
          kubectl rollout undo deployment/app-satc -n "${{ vars.K8S_NAMESPACE }}"
