name: Deploy Rolling Update

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: Tag da imagem Docker (ex. 0.0.2 ou SHA do commit)
        required: true
        default: "0.0.2"
      k8s_namespace:
        description: Namespace do Kubernetes
        required: true
        default: "satc-devops"

env:
  IMAGE_NAME: thiago-almeida-devops

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load project variables
        run: grep -v '^#' config/variables.env | grep -v '^$' >> "$GITHUB_ENV"

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GKE_CLUSTER_LOCATION }}

      - name: Render manifests
        env:
          NAMESPACE: ${{ inputs.k8s_namespace }}
          DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ inputs.image_tag }}
          APP_HOST: gremio.local
        run: |
          chmod +x k8s/render.sh
          ./k8s/render.sh

      - name: Apply base manifests
        run: |
          kubectl apply -f k8s/rendered/namespace.yaml
          kubectl apply -f k8s/rendered/deployment.yaml
          kubectl apply -f k8s/rendered/service.yaml
          kubectl apply -f k8s/rendered/hpa.yaml

      - name: Deploy image
        id: deploy_step
        env:
          NAMESPACE: ${{ inputs.k8s_namespace }}
        run: |
          kubectl set image deployment/app-satc \
            thiago-almeida-devops=${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ inputs.image_tag }} \
            -n "${NAMESPACE}"

      - name: Monitor rollout
        id: monitor
        env:
          NAMESPACE: ${{ inputs.k8s_namespace }}
        run: |
          kubectl rollout status deployment/app-satc -n "${NAMESPACE}" --timeout=5m

      - name: Auto rollback on failure
        if: failure() && steps.deploy_step.outcome == 'success'
        env:
          NAMESPACE: ${{ inputs.k8s_namespace }}
        run: |
          echo "Deploy falhou! Executando rollback..."
          kubectl rollout undo deployment/app-satc -n "${NAMESPACE}"
